port = 8889

# run with just a host, adding a port puts in testing mode for now
run:
	python3 doofus.py hugo

ryan:
	python3 doofus.py ryan

marc:
	python3 doofus.py marc


# run these concurrently for local testing. Don't change the ports
la:
	python3 doofus.py hugo 8825
lb:
	python3 doofus.py hugo 8826

# add test modules as they are impelemented
test:
	# first remove any files generated by test
	rm -f test*dfs.json 
	python3 test.py dfs dfsm
